"use client";
import Link from "next/link";import {useRef,useState} from "react";import {getDictionary,type Locale} from "@/lib/i18n";import {track} from "./analytics";
type Field="name"|"email"|"phone"|"residence"|"destination"|"goal"|"budget"|"timeline"|"contact"|"message"|"consent";
export function BuyerForm({locale}:{locale:Locale}){const d=getDictionary(locale),[status,setStatus]=useState<"idle"|"sending"|"success"|"duplicate"|"error">("idle"),[errors,setErrors]=useState<Field[]>([]),id=useRef(crypto.randomUUID()),started=useRef(false);
 const begin=()=>{if(!started.current){started.current=true;track("buyer_brief_start",{locale})}};
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setStatus("sending");setErrors([]);const form=event.currentTarget,data=Object.fromEntries(new FormData(form));const payload={...data,submissionId:id.current,locale,consent:data.consent==="on"};try{const res=await fetch("/api/buyer-brief",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),json=await res.json() as {code:string;fields?:Field[]};if(res.ok){const duplicate=json.code==="duplicate";setStatus(duplicate?"duplicate":"success");track("buyer_brief_complete",{locale,status:duplicate?"duplicate":"accepted"});form.reset();return}if(json.code==="invalid"){setErrors(json.fields||[]);setStatus("idle");requestAnimationFrame(()=>form.querySelector<HTMLElement>("[aria-invalid=true]")?.focus());return}setStatus("error")}catch{setStatus("error")}}
 const invalid=(f:Field)=>errors.includes(f),err=(f:Field)=><>{invalid(f)&&<p className="field-error" id={`${f}-error`}>{d.brief.invalid}</p>}</>;
 if(status==="success"||status==="duplicate")return <div className="form success" role="status"><div className="success-mark">✓</div><h2>{status==="duplicate"?d.brief.duplicate:d.brief.successTitle}</h2>{status==="success"&&<p>{d.brief.successText}</p>}<button className="button secondary" type="button" onClick={()=>{id.current=crypto.randomUUID();setStatus("idle")}}>{d.brief.startOver}</button></div>;
 return <form className="form" noValidate onSubmit={submit} onFocus={begin} aria-label={d.brief.title}>
  {status==="error"&&<div className="form-status" role="alert">{d.brief.retryText}</div>}
  <div className="field hp" aria-hidden="true"><label htmlFor="website">{d.brief.fields.website}</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div>
  <div className="field-grid">
   {(["name","email","phone","residence","destination","budget"] as const).map(f=><div className="field" key={f}><label htmlFor={f}>{d.brief.fields[f]}</label><input id={f} name={f} type={f==="email"?"email":f==="phone"?"tel":"text"} placeholder={d.brief.placeholders[f]} autoComplete={f==="name"?"name":f==="email"?"email":f==="phone"?"tel":"off"} aria-invalid={invalid(f)} aria-describedby={invalid(f)?`${f}-error`:undefined} required/>{err(f)}</div>)}
  </div>
  <div className="field"><label htmlFor="goal">{d.brief.fields.goal}</label><select id="goal" name="goal" defaultValue="" aria-invalid={invalid("goal")} required><option value="" disabled>{d.brief.options.select}</option>{d.brief.options.goals.map(o=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select>{err("goal")}</div>
  <div className="field"><label htmlFor="timeline">{d.brief.fields.timeline}</label><select id="timeline" name="timeline" defaultValue="" aria-invalid={invalid("timeline")} required><option value="" disabled>{d.brief.options.select}</option>{d.brief.options.timelines.map(o=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select>{err("timeline")}</div>
  <fieldset className="fieldset"><legend>{d.brief.fields.contact}</legend><div className="radio-row">{d.brief.options.contacts.map((o,i)=><label className="radio" key={o[0]}><input type="radio" name="contact" value={o[0]} defaultChecked={i===0}/>{o[1]}</label>)}</div>{err("contact")}</fieldset>
  <div className="field"><label htmlFor="message">{d.brief.fields.message}</label><textarea id="message" name="message" placeholder={d.brief.placeholders.message} aria-invalid={invalid("message")} aria-describedby={invalid("message")?"message-error":undefined}/>{err("message")}</div>
  <label className="consent"><input type="checkbox" name="consent" aria-invalid={invalid("consent")} aria-describedby={invalid("consent")?"consent-error":undefined} required/><span>{d.brief.fields.consent} <Link className="text-link" href={`/${locale}/privacy`}>{d.footer.privacy}</Link>{err("consent")}</span></label>
  <button className="button" type="submit" disabled={status==="sending"}>{status==="sending"?d.brief.submitting:d.brief.submit}</button>
 </form>}
