import Link from "next/link";
import { notFound } from "next/navigation";
import { getDictionary, isLocale } from "@/lib/i18n";

export default async function Home({params}:{params:Promise<{locale:string}>}){const {locale}=await params;if(!isLocale(locale))notFound();const d=getDictionary(locale);const countries=Object.entries(d.destinations.countries).slice(0,3);return <>
 <section className="hero"><div className="hero-main"><div className="hero-copy"><p className="eyebrow">{d.common.eyebrow}</p><h1 className="display">{d.home.title}</h1><p className="lead">{d.home.intro}</p><div className="actions"><Link className="button" href={`/${locale}/buyer-brief`}>{d.common.start}</Link><Link className="button secondary" href={`/${locale}/destinations`}>{d.common.explore}</Link></div></div><p className="eyebrow">US BASED · INTERNATIONAL SCOPE</p></div><aside className="hero-side"><span className="hero-mark">PRIVATE / CONSIDERED / GLOBAL</span><h2>{d.home.panelTitle}</h2><p>{d.home.panelText}</p></aside></section>
 <section className="section"><div className="shell"><div className="section-heading"><p className="eyebrow">01 / APPROACH</p><h2>{d.home.pillarsTitle}</h2></div><div className="grid-3">{d.home.pillars.map((p,i)=><article className="card" key={p[0]}><span className="number">0{i+1}</span><h3>{p[0]}</h3><p>{p[1]}</p></article>)}</div></div></section>
 <section className="section dark"><div className="shell"><div className="section-heading"><p className="eyebrow" style={{color:"#b8cbc3"}}>02 / MARKETS</p><div><h2>{d.home.destinationsTitle}</h2><p className="lead" style={{color:"#c8d4cf"}}>{d.home.destinationsText}</p></div></div><div className="destination-grid">{countries.map(([slug,c])=><article className="destination" key={slug}><span className="eyebrow" style={{color:"#aebfb8"}}>0{countries.findIndex(x=>x[0]===slug)+1}</span><h3>{c[0]}</h3><p>{c[1]}</p><Link className="text-link" href={`/${locale}/destinations/${slug}`}>{d.common.learn}</Link></article>)}</div><div style={{marginTop:"3rem"}}><Link className="button" style={{background:"var(--white)",color:"var(--green)"}} href={`/${locale}/destinations`}>{d.common.explore}</Link></div></div></section>
 <section className="section"><div className="shell split"><div><p className="eyebrow">03 / PROCESS</p><h2 className="statement">{d.home.processTitle}</h2></div><div className="quote-box"><p className="lead">{d.home.processText}</p><Link className="text-link" href={`/${locale}/buying-process`}>{d.common.learn}</Link></div></div></section>
 <section className="section tint"><div className="narrow" style={{textAlign:"center"}}><p className="eyebrow">PRIVATE BRIEF</p><h2 className="page-title">{d.home.ctaTitle}</h2><p className="lead" style={{marginInline:"auto",marginBottom:"2rem"}}>{d.home.ctaText}</p><Link className="button" href={`/${locale}/buyer-brief`}>{d.common.start}</Link></div></section>
 </>}
