import Link from "next/link";
import { notFound } from "next/navigation";
import { AbstractArt } from "@/components/abstract-art";
import { getDictionary, isLocale } from "@/lib/i18n";

export default async function Home({params}:{params:Promise<{locale:string}>}){const {locale}=await params;if(!isLocale(locale))notFound();const d=getDictionary(locale);const countries=Object.entries(d.destinations.countries).slice(0,3);return <>
 <section className="hero"><div className="shell hero-grid"><div className="hero-copy reveal"><p className="eyebrow">{d.common.eyebrow}</p><h1 className="display">{d.home.title}</h1><p className="lead">{d.home.intro}</p><div className="actions"><Link className="button" href={`/${locale}/buyer-brief`}>{d.common.start}<span aria-hidden="true">↗</span></Link><Link className="button secondary" href={`/${locale}/destinations`}>{d.common.explore}</Link></div></div><div className="hero-visual reveal reveal--delay"><AbstractArt/><div className="hero-note"><span className="eyebrow">PRIVATE / CONSIDERED / GLOBAL</span><h2>{d.home.panelTitle}</h2><p>{d.home.panelText}</p></div></div></div><div className="shell hero-foot"><span>US BASED</span><span>INTERNATIONAL SCOPE</span><span>EST. / 2026</span></div></section>
 <section className="section approach"><div className="shell"><div className="section-heading"><p className="eyebrow">01 / APPROACH</p><h2>{d.home.pillarsTitle}</h2></div><div className="grid-3">{d.home.pillars.map((p,i)=><article className="card" key={p[0]}><span className="number">0{i+1}</span><h3>{p[0]}</h3><p>{p[1]}</p></article>)}</div></div></section>
 <section className="section dark markets"><div className="shell"><div className="section-heading"><p className="eyebrow">02 / MARKETS</p><div><h2>{d.home.destinationsTitle}</h2><p className="lead">{d.home.destinationsText}</p></div></div><div className="destination-grid">{countries.map(([slug,c],i)=><article className="destination" key={slug}><span className="eyebrow">0{i+1}</span><h3>{c[0]}</h3><p>{c[1]}</p><Link className="text-link" href={`/${locale}/destinations/${slug}`}>{d.common.learn}</Link></article>)}</div><Link className="button light-button" href={`/${locale}/destinations`}>{d.common.explore}<span aria-hidden="true">↗</span></Link></div></section>
 <section className="section process-feature"><div className="shell split"><div><p className="eyebrow">03 / PROCESS</p><h2 className="statement">{d.home.processTitle}</h2></div><div className="process-aside"><span className="process-index">03—06</span><p className="lead">{d.home.processText}</p><Link className="text-link" href={`/${locale}/buying-process`}>{d.common.learn}</Link></div></div></section>
 <section className="section cta-panel"><div className="shell cta-grid"><AbstractArt compact/><div><p className="eyebrow">PRIVATE BRIEF</p><h2 className="page-title">{d.home.ctaTitle}</h2><p className="lead">{d.home.ctaText}</p><Link className="button" href={`/${locale}/buyer-brief`}>{d.common.start}<span aria-hidden="true">↗</span></Link></div></div></section>
 </>}
