import { Resend } from "resend";
import type { BuyerBrief } from "@/lib/brief-schema";
import { getDictionary } from "@/lib/i18n";
import type { EmailAdapter } from "./types";
const escape=(s:string)=>s.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]!));
const labels={en:{subject:"We received your private Buyer Brief",hello:"Hello",body:"Thank you for sharing your purchase brief. Our team will review it and normally respond within two US business days.",note:"Submission does not create an agency or advisory relationship."},ru:{subject:"Мы получили ваш Buyer Brief",hello:"Здравствуйте",body:"Спасибо за ваш запрос. Команда рассмотрит его и обычно ответит в течение двух рабочих дней в США.",note:"Отправка запроса не создаёт агентских или консультационных отношений."},es:{subject:"Hemos recibido su Buyer Brief",hello:"Hola",body:"Gracias por compartir su brief. Nuestro equipo lo revisará y normalmente responderá en dos días laborables de EE. UU.",note:"El envío no crea una relación de agencia o asesoría."},ar:{subject:"تم استلام ملخص المشتري",hello:"مرحبًا",body:"شكرًا لمشاركة ملخص الشراء. سيراجعه فريقنا ويرد عادة خلال يومي عمل في الولايات المتحدة.",note:"لا يؤدي الإرسال إلى إنشاء علاقة وكالة أو استشارة."}} as const;
export function confirmationTemplate(brief:BuyerBrief){const t=labels[brief.locale],dir=brief.locale==="ar"?"rtl":"ltr";return{subject:t.subject,html:`<!doctype html><html lang="${brief.locale}" dir="${dir}"><body style="margin:0;background:#f4f0e7;color:#11251f;font-family:Arial,sans-serif"><div style="max-width:620px;margin:auto;padding:48px 24px"><p style="letter-spacing:2px;font-size:12px">MERIDIAN PRIVATE</p><h1 style="font-family:Georgia,serif;font-weight:normal">${t.hello} ${escape(brief.name)},</h1><p style="line-height:1.7">${t.body}</p><hr style="border:0;border-top:1px solid #c8c3b8;margin:32px 0"><p style="font-size:12px;color:#52635c">${t.note}</p></div></body></html>`};}
export function ownerTemplate(brief:BuyerBrief){const d=getDictionary(brief.locale),rows:[[string,string],[string,string]][]=[];void rows;const values:[[string,string],[string,string],[string,string],[string,string],[string,string],[string,string],[string,string],[string,string],[string,string]]=[[d.brief.fields.name,brief.name],[d.brief.fields.email,brief.email],[d.brief.fields.phone,brief.phone],[d.brief.fields.residence,brief.residence],[d.brief.fields.destination,brief.destination],[d.brief.fields.goal,brief.goal],[d.brief.fields.budget,brief.budget],[d.brief.fields.timeline,brief.timeline],[d.brief.fields.contact,brief.contact]];return{subject:`New Buyer Brief · ${brief.destination}`,html:`<h1>New Buyer Brief</h1>${values.map(([k,v])=>`<p><strong>${escape(k)}:</strong> ${escape(v)}</p>`).join("")}<p><strong>${escape(d.brief.fields.message)}:</strong><br>${escape(brief.message).replace(/\n/g,"<br>")}</p><p>Submission ID: ${escape(brief.submissionId)}</p>`};}
export class ResendAdapter implements EmailAdapter{private client:Resend;constructor(private key:string,private from:string,private owner:string){this.client=new Resend(key)}private async send(input:{from:string;to:string[];subject:string;html:string}){const {error}=await this.client.emails.send(input);if(error)throw new Error("email_delivery_failed")};async notifyOwner(brief:BuyerBrief){await this.send({from:this.from,to:[this.owner],...ownerTemplate(brief)})}async confirmBuyer(brief:BuyerBrief){await this.send({from:this.from,to:[brief.email],...confirmationTemplate(brief)})}}
